gitリポジトリのrootにbuildファイルが存在した場合は実行し、失敗したらコミットを許可しない

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -10,10 +10,28 @@ fi
 
 ticket="$(extractTicketId)"
 if [ -n "${ticket}" ]; then
-    appendMsgTo1stLine "$1" "${ticket}"
+     appendMsgTo1stLine "$1" "${ticket}"
     
      read git_comment < "$1"
      # add closes?
 #     echo "comment :: $git_comment"
      echo $git_comment | sed -e "s/ #close refs/ closes/" > $1
+     
+     echo "----------------"
+     echo "$git_comment"
+     echo "----------------"
+     if expr "$git_comment" : ".*#close" >/dev/null; then
+        echo "close ticket"
+        echo "check build..."
+        if [ -f ./build ]; then
+          ./build
+          if [ $? -ne 0 ]; then
+              echo "build error!!"
+              exit 1
+          fi
+        else
+          echo "build file not exist..."
+        fi
+        echo "commit ok"
+     fi
 fi
